window.AI4A_CENTERS = [
  {
    "id": "AI4A-001",
    "name": "Trung tâm Can thiệp Đăng Minh",
    "city": "Hà Nội",
    "district": "Hoàng Mai",
    "address": "CC Kim Văn Kim Lũ, Đại Kim, Hoàng Mai, Hà Nội",
    "phone": "097.948.1988",
    "email": "",
    "website": "https://canthiepdangminh.com/",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "",
    "model": "Giáo dục đặc biệt, can thiệp trẻ đặc biệt",
    "lat": 20.9752,
    "lng": 105.8309,
    "status": "Need verify",
    "source": "https://canthiepdangminh.com/",
    "verifyStatus": "Can xac minh lai",
    "note": "Nguồn crawl 2026-05-20; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-002",
    "name": "Trung tâm Can thiệp sớm Tâm Đức - Cơ sở 1",
    "city": "Hà Nội",
    "district": "Hoàng Mai",
    "address": "Ngõ 293 Phố Tân Mai, Tân Mai, Hoàng Mai, Hà Nội",
    "phone": "0375.499.495; 0336.068.870",
    "email": "ctstamduchanoi@gmail.com",
    "website": "https://canthiepsomtamduc.org/",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "",
    "model": "Giáo dục và hỗ trợ trẻ có nhu cầu giáo dục đặc biệt",
    "lat": 20.97968,
    "lng": 105.84598,
    "status": "Ready",
    "source": "https://canthiepsomtamduc.org/",
    "verifyStatus": "Can xac minh lai",
    "note": "Nguồn crawl 2026-05-20"
  },
  {
    "id": "AI4A-003",
    "name": "Trung tâm Can thiệp sớm Tâm Đức - Cơ sở 2",
    "city": "Hà Nội",
    "district": "Hai Bà Trưng",
    "address": "Ngõ 156 Phố Lạc Trung, Thanh Lương, Hai Bà Trưng, Hà Nội",
    "phone": "0375.499.495; 0336.068.870",
    "email": "ctstamduchanoi@gmail.com",
    "website": "https://canthiepsomtamduc.org/",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "",
    "model": "Giáo dục và hỗ trợ trẻ có nhu cầu giáo dục đặc biệt",
    "lat": 21.00078,
    "lng": 105.86034,
    "status": "Ready",
    "source": "https://canthiepsomtamduc.org/",
    "verifyStatus": "Can xac minh lai",
    "note": "Nguồn crawl 2026-05-20"
  },
  {
    "id": "AI4A-004",
    "name": "Trung tâm Can thiệp sớm Minh Tâm",
    "city": "Hà Nội",
    "district": "Thanh Xuân",
    "address": "Số 43 Ngõ 1 Ngụy Như Kon Tum, Thanh Xuân, Hà Nội",
    "phone": "096.72777.08",
    "email": "canthiepsomminhtam@gmail.com",
    "website": "https://chamnoibinhminh.com/lien-he/",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "",
    "model": "Can thiệp sớm",
    "lat": 21.0025,
    "lng": 105.8055,
    "status": "Need verify",
    "source": "https://chamnoibinhminh.com/lien-he/",
    "verifyStatus": "Can xac minh lai",
    "note": "Nguồn crawl 2026-05-20; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-005",
    "name": "Trung tâm Can thiệp sớm và Phục hồi chức năng CPCare - Hà Nội",
    "city": "Hà Nội",
    "district": "Bắc Từ Liêm",
    "address": "Nhà L2, ngõ 210 Hoàng Quốc Việt, Bắc Từ Liêm, Hà Nội",
    "phone": "0356.227.632; 078.5555.803; 024.7300.6168",
    "email": "CPCarevn@gmail.com",
    "website": "https://phuchoichucnangcpcare.com.vn/lien-he/",
    "type": "Trung tâm can thiệp / phục hồi chức năng",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "",
    "model": "Can thiệp sớm và phục hồi chức năng",
    "lat": 21.04627,
    "lng": 105.79166,
    "status": "Ready",
    "source": "https://phuchoichucnangcpcare.com.vn/lien-he/",
    "verifyStatus": "Can xac minh lai",
    "note": "Nguồn crawl 2026-05-20"
  },
  {
    "id": "AI4A-006",
    "name": "Trung tâm Can thiệp sớm và Phục hồi chức năng CPCare - TP.HCM",
    "city": "TP.HCM",
    "district": "Quận 10",
    "address": "163/14/48 Tô Hiến Thành, Phường 13, Quận 10, TP.HCM",
    "phone": "078.5555.803; 028.7304.6168",
    "email": "CPCarevn@gmail.com",
    "website": "https://phuchoichucnangcpcare.com.vn/lien-he/",
    "type": "Trung tâm can thiệp / phục hồi chức năng",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "",
    "model": "Can thiệp sớm và phục hồi chức năng",
    "lat": 10.77322,
    "lng": 106.66803,
    "status": "Ready",
    "source": "https://phuchoichucnangcpcare.com.vn/lien-he/",
    "verifyStatus": "Can xac minh lai",
    "note": "Nguồn crawl 2026-05-20"
  },
  {
    "id": "AI4A-007",
    "name": "Trung tâm Can thiệp sớm Mai Khôi",
    "city": "Hà Nội",
    "district": "Ngọc Hà",
    "address": "Số 40, Ngách 35, Phố Văn Cao, Phường Ngọc Hà, Hà Nội",
    "phone": "0358.100.600",
    "email": "",
    "website": "https://vddn.vn/trung-tam-can-thiep-som-mai-khoi/",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "",
    "model": "Can thiệp sớm",
    "lat": 21.0395,
    "lng": 105.817,
    "status": "Need verify",
    "source": "https://vddn.vn/trung-tam-can-thiep-som-mai-khoi/",
    "verifyStatus": "Can xac minh lai",
    "note": "Nguồn crawl 2026-05-20; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-008",
    "name": "Trung tâm Hỗ trợ phát triển giáo dục hòa nhập Gõ Là Mở",
    "city": "TP.HCM",
    "district": "Phú Nhuận",
    "address": "88/50 Đào Duy Anh, Phường Đức Nhuận, TP.HCM",
    "phone": "0909.797.183",
    "email": "",
    "website": "https://golamo.vn/thong-tin-chung-ve-trung-tam",
    "type": "Trung tâm giáo dục hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "",
    "model": "Can thiệp trẻ tự kỷ, tăng động, chậm ngôn ngữ, chậm nhận thức",
    "lat": 10.80169,
    "lng": 106.67475,
    "status": "Ready",
    "source": "https://golamo.vn/thong-tin-chung-ve-trung-tam",
    "verifyStatus": "Can xac minh lai",
    "note": "Nguồn crawl 2026-05-20"
  },
  {
    "id": "AI4A-009",
    "name": "Trung tâm Can thiệp sớm và Giáo dục hòa nhập Hoa Mặt Trời",
    "city": "Bình Dương",
    "district": "Thuận An",
    "address": "79C/9 Lái Thiêu 42, Phường Lái Thiêu, Thành phố Thuận An, Bình Dương",
    "phone": "",
    "email": "",
    "website": "https://hoamattroi.edu.vn/",
    "type": "Trung tâm can thiệp / giáo dục hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "18 tháng - 12 tuổi; 2 - 16 tuổi",
    "model": "Can thiệp trẻ rối loạn phổ tự kỷ, ADHD, chậm nói, rối loạn phát triển",
    "lat": 10.90505,
    "lng": 106.69922,
    "status": "Ready",
    "source": "https://hoamattroi.edu.vn/",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn crawl 2026-05-20; địa chỉ lấy từ website chính thức/kết quả tìm kiếm"
  },
  {
    "id": "AI4A-010",
    "name": "Trung tâm Can thiệp sớm Phúc Uyên",
    "city": "Tây Ninh",
    "district": "Hòa Thành",
    "address": "Số 46 Đường số 15, Khu phố Long Đại, Phường Long Thành Bắc, Hòa Thành, Tây Ninh",
    "phone": "0856.260.179",
    "email": "tin.letruongtphcm@gmail.com",
    "website": "https://canthiepsomphucuyen.com/",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "",
    "model": "Âm ngữ trị liệu, chậm phát triển, tự kỷ, tham vấn tâm lý",
    "lat": 11.28513,
    "lng": 106.12037,
    "status": "Ready",
    "source": "https://canthiepsomphucuyen.com/",
    "verifyStatus": "Can xac minh lai",
    "note": "Nguồn crawl 2026-05-20"
  },
  {
    "id": "AI4A-011",
    "name": "Trường chuyên biệt Bình Minh - Cơ sở 1",
    "city": "TP.HCM",
    "district": "Tân Phú",
    "address": "Số 10 đường Nguyễn Thái Học, phường Tân Thành, quận Tân Phú, TP.HCM",
    "phone": "(028).3.812.1865",
    "email": "",
    "website": "https://sfccharity.com/thong-tin/truong-chuyen-biet-binh-minh/",
    "type": "Trường chuyên biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "",
    "model": "Giáo dục đặc biệt trẻ chậm phát triển, tự kỷ",
    "lat": 10.78734,
    "lng": 106.6256,
    "status": "Ready",
    "source": "https://sfccharity.com/thong-tin/truong-chuyen-biet-binh-minh/",
    "verifyStatus": "Can xac minh lai",
    "note": "Nguồn crawl 2026-05-20"
  },
  {
    "id": "AI4A-012",
    "name": "Trường chuyên biệt Bình Minh - Cơ sở 2",
    "city": "TP.HCM",
    "district": "Tân Phú",
    "address": "Số 138/6 đường Diệp Minh Châu, phường Tân Sơn Nhì, quận Tân Phú, TP.HCM",
    "phone": "(028).3.812.7419",
    "email": "",
    "website": "https://sfccharity.com/thong-tin/truong-chuyen-biet-binh-minh/",
    "type": "Trường chuyên biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "",
    "model": "Giáo dục đặc biệt trẻ chậm phát triển, tự kỷ",
    "lat": 10.79233,
    "lng": 106.62474,
    "status": "Ready",
    "source": "https://sfccharity.com/thong-tin/truong-chuyen-biet-binh-minh/",
    "verifyStatus": "Can xac minh lai",
    "note": "Nguồn crawl 2026-05-20"
  },
  {
    "id": "AI4A-013",
    "name": "Trường mầm non đặc biệt Mykyo",
    "city": "Hà Nội",
    "district": "Cầu Giấy",
    "address": "Số 3, Ngõ 61/26/1 Trần Duy Hưng, Hà Nội",
    "phone": "0987.449.223",
    "email": "",
    "website": "http://www.Myokoschool.com",
    "type": "Trường chuyên biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "Mẫu giáo",
    "model": "Dạy trẻ tự kỷ, ADHD",
    "lat": 21.0061,
    "lng": 105.7954,
    "status": "Need verify",
    "source": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "verifyStatus": "Nguon cu - can xac minh",
    "note": "Nguồn danh sách 2012; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-014",
    "name": "Trường Tiểu học Bình Minh",
    "city": "Hà Nội",
    "district": "Hoàn Kiếm",
    "address": "80 Thợ Nhuộm, Quận Hoàn Kiếm, Hà Nội",
    "phone": "04.942.4359; 04.822.4012",
    "email": "",
    "website": "",
    "type": "Trường chuyên biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "6 - 10",
    "model": "Dạy văn hóa cho trẻ thiểu năng trí tuệ",
    "lat": 21.028291,
    "lng": 105.844088,
    "status": "Need verify",
    "source": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "verifyStatus": "Nguon cu - can xac minh",
    "note": "Nguồn danh sách 2012"
  },
  {
    "id": "AI4A-015",
    "name": "Trường chuyên biệt Bình Minh",
    "city": "Hà Nội",
    "district": "Đông Anh",
    "address": "Thôn Đài Bi, Xã Uy Nỗ, huyện Đông Anh, Hà Nội",
    "phone": "04.965.0489",
    "email": "",
    "website": "",
    "type": "Trường chuyên biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "",
    "model": "Giáo dục tiểu học, dạy nghề cho học sinh khiếm thính",
    "lat": 21.139,
    "lng": 105.849,
    "status": "Need verify",
    "source": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "verifyStatus": "Nguon cu - can xac minh",
    "note": "Nguồn danh sách 2012; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-016",
    "name": "Trung tâm Phúc Tuệ",
    "city": "Hà Nội",
    "district": "Ba Đình",
    "address": "66 Phó Đức Chính, Quận Ba Đình, Hà Nội",
    "phone": "04.716.1159; 04.916.9602",
    "email": "",
    "website": "",
    "type": "Trung tâm giáo dục đặc biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "",
    "model": "Chăm sóc, dạy nghề cho trẻ chậm phát triển trí tuệ",
    "lat": 21.0436,
    "lng": 105.8414,
    "status": "Need verify",
    "source": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "verifyStatus": "Nguon cu - can xac minh",
    "note": "Nguồn danh sách 2012; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-017",
    "name": "Trường tư thục chuyên biệt Thảo Điền",
    "city": "TP.HCM",
    "district": "Thủ Đức",
    "address": "91 Thảo Điền, Phường Thảo Điền, TP.Thủ Đức, TP.HCM",
    "phone": "08.512.4592",
    "email": "",
    "website": "",
    "type": "Trường chuyên biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "",
    "model": "Dạy trẻ tự kỷ, chậm khôn",
    "lat": 10.8044,
    "lng": 106.737,
    "status": "Need verify",
    "source": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "verifyStatus": "Nguon cu - can xac minh",
    "note": "Nguồn danh sách 2012; địa danh Q2 cần cập nhật TP.Thủ Đức; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-018",
    "name": "Trường Mầm non 8",
    "city": "TP.HCM",
    "district": "Quận 3",
    "address": "Lý Chính Thắng, Quận 3, TP.HCM",
    "phone": "08.848.33.03",
    "email": "",
    "website": "",
    "type": "Trường / mầm non hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "",
    "model": "Giáo dục trẻ chậm khôn, tự kỷ",
    "lat": 10.7879,
    "lng": 106.6853,
    "status": "Need verify",
    "source": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "verifyStatus": "Nguon cu - can xac minh",
    "note": "Nguồn danh sách 2012; địa chỉ chưa đủ số nhà; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-019",
    "name": "Trường Tương Lai Quận 5 - Cơ sở 1",
    "city": "TP.HCM",
    "district": "Quận 5",
    "address": "27-29 Ngô Quyền, Phường 10, Quận 5, TP.HCM",
    "phone": "855.2429",
    "email": "",
    "website": "",
    "type": "Trường chuyên biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "",
    "model": "Giáo dục đặc biệt trẻ chậm khôn, tự kỷ, Down, khiếm thính",
    "lat": 10.7547,
    "lng": 106.6695,
    "status": "Need verify",
    "source": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "verifyStatus": "Nguon cu - can xac minh",
    "note": "Nguồn danh sách 2012; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-020",
    "name": "Trường Tương Lai Quận 5 - Cơ sở 2",
    "city": "TP.HCM",
    "district": "Quận 5",
    "address": "28 Trần Xuân Hòa, Phường 17, Quận 5, TP.HCM",
    "phone": "950.9159",
    "email": "",
    "website": "",
    "type": "Trường chuyên biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "",
    "model": "Giáo dục đặc biệt trẻ chậm khôn, tự kỷ, Down, khiếm thính",
    "lat": 10.7545,
    "lng": 106.6662,
    "status": "Need verify",
    "source": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "verifyStatus": "Nguon cu - can xac minh",
    "note": "Nguồn danh sách 2012; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-021",
    "name": "Trường chuyên biệt tư thục Ước Mơ",
    "city": "TP.HCM",
    "district": "Quận 10",
    "address": "284/4/10 Lý Thường Kiệt, Phường 14, Quận 10, TP.HCM",
    "phone": "864.5347",
    "email": "",
    "website": "",
    "type": "Trường chuyên biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "",
    "model": "Dạy trẻ tự kỷ và ADHD",
    "lat": 10.7734,
    "lng": 106.6589,
    "status": "Need verify",
    "source": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "verifyStatus": "Nguon cu - can xac minh",
    "note": "Nguồn danh sách 2012; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-022",
    "name": "Trường tư thục POOH PI",
    "city": "TP.HCM",
    "district": "Quận 10",
    "address": "22 lô C Trường Sơn, Phường 15, Quận 10, TP.HCM",
    "phone": "970.3936",
    "email": "",
    "website": "",
    "type": "Trường chuyên biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "",
    "model": "Giáo dục trẻ tự kỷ và chậm phát triển",
    "lat": 10.7818,
    "lng": 106.6637,
    "status": "Need verify",
    "source": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "verifyStatus": "Nguon cu - can xac minh",
    "note": "Nguồn danh sách 2012; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-023",
    "name": "Trường khuyết tật Gia Định",
    "city": "TP.HCM",
    "district": "Bình Thạnh",
    "address": "280 Bùi Hữu Nghĩa, Phường 2, Quận Bình Thạnh, TP.HCM",
    "phone": "803.0056",
    "email": "",
    "website": "",
    "type": "Trường chuyên biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "",
    "model": "Giáo dục trẻ chậm khôn, Down, tự kỷ",
    "lat": 10.8068,
    "lng": 106.6974,
    "status": "Need verify",
    "source": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "verifyStatus": "Nguon cu - can xac minh",
    "note": "Nguồn danh sách 2012; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-024",
    "name": "Trường tư thục chuyên biệt Khai Trí",
    "city": "TP.HCM",
    "district": "Bình Thạnh",
    "address": "214/25F Điện Biên Phủ, Phường 17, Quận Bình Thạnh, TP.HCM",
    "phone": "08.3518.0184; 08.3518.0253",
    "email": "",
    "website": "http://www.truongchuyenbietkhaitri.com",
    "type": "Trường chuyên biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "2 - 10",
    "model": "Dạy trẻ tự kỷ, khó khăn về nói/giao tiếp, ADHD, chậm phát triển",
    "lat": 10.8012,
    "lng": 106.7169,
    "status": "Need verify",
    "source": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "verifyStatus": "Nguon cu - can xac minh",
    "note": "Nguồn danh sách 2012"
  },
  {
    "id": "AI4A-025",
    "name": "Trường tư thục Giáo dục chuyên biệt Ban Mai",
    "city": "TP.HCM",
    "district": "Bình Thạnh",
    "address": "23/30 Đường D2, Phường 25, Quận Bình Thạnh, TP.HCM",
    "phone": "08.35.12.74.30",
    "email": "lienhe@truongbanmai.com",
    "website": "http://www.truongbanmai.com",
    "type": "Trường chuyên biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "",
    "model": "Dạy trẻ tự kỷ, Asperger, chậm khôn, ADHD",
    "lat": 10.80235,
    "lng": 106.7172,
    "status": "Need verify",
    "source": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "verifyStatus": "Nguon cu - can xac minh",
    "note": "Nguồn danh sách 2012"
  },
  {
    "id": "AI4A-026",
    "name": "Trường Mầm Non Nam Phương",
    "city": "TP.HCM",
    "district": "Bình Thạnh",
    "address": "153 Xô Viết Nghệ Tĩnh, Phường 17, Quận Bình Thạnh, TP.HCM",
    "phone": "08.6285.3711; 0934.124.245; 0905.830.668",
    "email": "",
    "website": "",
    "type": "Mầm non hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "",
    "model": "Giáo dục trẻ mẫu giáo bình thường và trẻ tự kỷ",
    "lat": 10.804,
    "lng": 106.7102,
    "status": "Need verify",
    "source": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "verifyStatus": "Nguon cu - can xac minh",
    "note": "Nguồn danh sách 2012; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-027",
    "name": "Trường tiểu học tư thục chuyên biệt Anh Vương",
    "city": "TP.HCM",
    "district": "Tân Bình",
    "address": "86 Đường Cống Lở, Phường 15, Quận Tân Bình, TP.HCM",
    "phone": "08.73.004.120; 0918.018.227; 0907.575.369",
    "email": "anhvuongspecschool@gmail.com",
    "website": "http://anhvuongspecschool.edu.vn/",
    "type": "Trường chuyên biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "",
    "model": "Dạy trẻ tự kỷ và trẻ chậm khôn",
    "lat": 10.81312,
    "lng": 106.63318,
    "status": "Need verify",
    "source": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "verifyStatus": "Nguon cu - can xac minh",
    "note": "Nguồn danh sách 2012"
  },
  {
    "id": "AI4A-028",
    "name": "Trường tư thục Giáo dục chuyên biệt Niềm Tin",
    "city": "TP.HCM",
    "district": "Phú Nhuận",
    "address": "16/2/8 Đặng Văn Ngữ, Phường 10, Quận Phú Nhuận, TP.HCM",
    "phone": "991.3839",
    "email": "",
    "website": "",
    "type": "Trường chuyên biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "",
    "model": "Dạy trẻ chậm khôn, tự kỷ",
    "lat": 10.7966,
    "lng": 106.6777,
    "status": "Need verify",
    "source": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "verifyStatus": "Nguon cu - can xac minh",
    "note": "Nguồn danh sách 2012; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-029",
    "name": "Edunow - Trụ sở chính",
    "city": "Đà Nẵng",
    "district": "Liên Chiểu",
    "address": "11 Thích Quảng Đức, Liên Chiểu, TP Đà Nẵng",
    "phone": "0974.584.748",
    "email": "edunowvietnam@gmail.com",
    "website": "https://new.edunow.edu.vn/gioi-thieu/",
    "type": "Trung tâm can thiệp / giáo dục đặc biệt",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "",
    "model": "Can thiệp trẻ tự kỷ, chậm nói, rối loạn ngôn ngữ, ADHD; bán trú, 1:1, tiền tiểu học",
    "lat": 16.06716,
    "lng": 108.15198,
    "status": "Ready",
    "source": "https://new.edunow.edu.vn/gioi-thieu/",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn chính thức Edunow, crawl 2026-05-20"
  },
  {
    "id": "AI4A-030",
    "name": "Edunow - Cơ sở Hải Vân",
    "city": "Đà Nẵng",
    "district": "Hải Vân",
    "address": "1456 Mê Linh, Phường Hải Vân, TP Đà Nẵng",
    "phone": "0974.584.748",
    "email": "edunowvietnam@gmail.com",
    "website": "https://new.edunow.edu.vn/gioi-thieu/",
    "type": "Trung tâm can thiệp / giáo dục đặc biệt",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "",
    "model": "Can thiệp trẻ tự kỷ, chậm nói, rối loạn ngôn ngữ, ADHD; bán trú, 1:1, tiền tiểu học",
    "lat": 16.11968,
    "lng": 108.12831,
    "status": "Ready",
    "source": "https://new.edunow.edu.vn/gioi-thieu/",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn chính thức Edunow, crawl 2026-05-20"
  },
  {
    "id": "AI4A-031",
    "name": "Edunow - Cơ sở Thanh Bình",
    "city": "Đà Nẵng",
    "district": "Thanh Bình",
    "address": "27 Lê Văn Long, Phường Thanh Bình, TP Đà Nẵng",
    "phone": "0974.584.748",
    "email": "edunowvietnam@gmail.com",
    "website": "https://new.edunow.edu.vn/gioi-thieu/",
    "type": "Trung tâm can thiệp / giáo dục đặc biệt",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "",
    "model": "Can thiệp trẻ tự kỷ, chậm nói, rối loạn ngôn ngữ, ADHD; bán trú, 1:1, tiền tiểu học",
    "lat": 16.07562,
    "lng": 108.21387,
    "status": "Ready",
    "source": "https://new.edunow.edu.vn/gioi-thieu/",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn chính thức Edunow, crawl 2026-05-20"
  },
  {
    "id": "AI4A-032",
    "name": "Trường Chuyên biệt Tương Lai Đà Nẵng - Cơ sở Hải Châu",
    "city": "Đà Nẵng",
    "district": "Hải Châu",
    "address": "22 Trần Bình Trọng, Quận Hải Châu, TP Đà Nẵng",
    "phone": "0236.3897.388",
    "email": "",
    "website": "https://sfccharity.com/thong-tin/truong-chuyen-biet-tuong-lai-da-nang/",
    "type": "Trường chuyên biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "",
    "model": "Dạy văn hóa, phục hồi chức năng, kỹ năng sống, dạy nghề, hướng nghiệp cho học sinh khuyết tật",
    "lat": 16.06632,
    "lng": 108.21919,
    "status": "Ready",
    "source": "https://sfccharity.com/thong-tin/truong-chuyen-biet-tuong-lai-da-nang/",
    "verifyStatus": "Cần xác minh lại",
    "note": "Có nguồn báo chí xác nhận trường có 2 cơ sở Hải Châu và Cẩm Lệ"
  },
  {
    "id": "AI4A-033",
    "name": "Trường Chuyên biệt Tương Lai Đà Nẵng - Cơ sở Cẩm Lệ",
    "city": "Đà Nẵng",
    "district": "Cẩm Lệ",
    "address": "88A Huy Cận, Quận Cẩm Lệ, TP Đà Nẵng",
    "phone": "",
    "email": "",
    "website": "https://nhandan.vn/buoc-toi-tuong-lai-tu-ngoi-truong-chuyen-biet-post751145.html",
    "type": "Trường chuyên biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "",
    "model": "Giáo dục chuyên biệt cho học sinh khiếm khuyết; có học sinh khuyết tật trí tuệ, tự kỷ",
    "lat": 16.03184,
    "lng": 108.21756,
    "status": "Ready",
    "source": "https://nhandan.vn/buoc-toi-tuong-lai-tu-ngoi-truong-chuyen-biet-post751145.html",
    "verifyStatus": "Cần xác minh lại",
    "note": "Báo Nhân Dân ghi địa chỉ 88A Huy Cận; một số nguồn khác ghi 102 Huy Cận nên cần đối chiếu"
  },
  {
    "id": "AI4A-034",
    "name": "Trung tâm Hỗ trợ phát triển giáo dục hòa nhập Đà Nẵng",
    "city": "Đà Nẵng",
    "district": "Liên Chiểu",
    "address": "40 Lý Chính Thắng, Hòa Khánh, TP Đà Nẵng",
    "phone": "",
    "email": "",
    "website": "https://tieuhocdongphu.edu.vn/laws/detail/V-v-huong-dan-cong-tac-giao-duc-hoa-nhap-cho-hoc-sinh-khuyet-tat-tai-cac-co-so-giao-duc-pho-thong-tu-nam-hoc-2025-2026-153/?download=1&id=0",
    "type": "Trung tâm giáo dục hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "",
    "model": "Hỗ trợ phát triển giáo dục hòa nhập",
    "lat": 16.0676,
    "lng": 108.15456,
    "status": "Ready",
    "source": "https://tieuhocdongphu.edu.vn/laws/detail/V-v-huong-dan-cong-tac-giao-duc-hoa-nhap-cho-hoc-sinh-khuyet-tat-tai-cac-co-so-giao-duc-pho-thong-tu-nam-hoc-2025-2026-153/?download=1&id=0",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn văn bản hướng dẫn giáo dục hòa nhập năm học 2025-2026"
  },
  {
    "id": "AI4A-035",
    "name": "Trung tâm Hỗ trợ phát triển giáo dục hòa nhập Hướng Dương Vàng",
    "city": "Đà Nẵng",
    "district": "Quảng Phú",
    "address": "57 Lê Nhân Tông, Phường Quảng Phú, TP Đà Nẵng",
    "phone": "",
    "email": "",
    "website": "https://tieuhocdongphu.edu.vn/laws/detail/V-v-huong-dan-cong-tac-giao-duc-hoa-nhap-cho-hoc-sinh-khuyet-tat-tai-cac-co-so-giao-duc-pho-thong-tu-nam-hoc-2025-2026-153/?download=1&id=0",
    "type": "Trung tâm giáo dục hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "",
    "model": "Hỗ trợ phát triển giáo dục hòa nhập",
    "lat": 15.595,
    "lng": 108.5,
    "status": "Need verify",
    "source": "https://tieuhocdongphu.edu.vn/laws/detail/V-v-huong-dan-cong-tac-giao-duc-hoa-nhap-cho-hoc-sinh-khuyet-tat-tai-cac-co-so-giao-duc-pho-thong-tu-nam-hoc-2025-2026-153/?download=1&id=0",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn văn bản hướng dẫn giáo dục hòa nhập năm học 2025-2026; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-036",
    "name": "Trung tâm Hỗ trợ phát triển giáo dục hòa nhập Sơn Ca",
    "city": "Đà Nẵng",
    "district": "Hải Châu",
    "address": "99/34 Núi Thành, Phường Hải Châu, TP Đà Nẵng",
    "phone": "",
    "email": "",
    "website": "https://tieuhocdongphu.edu.vn/laws/detail/V-v-huong-dan-cong-tac-giao-duc-hoa-nhap-cho-hoc-sinh-khuyet-tat-tai-cac-co-so-giao-duc-pho-thong-tu-nam-hoc-2025-2026-153/?download=1&id=0",
    "type": "Trung tâm giáo dục hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "",
    "model": "Hỗ trợ phát triển giáo dục hòa nhập",
    "lat": 16.0432,
    "lng": 108.2182,
    "status": "Need verify",
    "source": "https://tieuhocdongphu.edu.vn/laws/detail/V-v-huong-dan-cong-tac-giao-duc-hoa-nhap-cho-hoc-sinh-khuyet-tat-tai-cac-co-so-giao-duc-pho-thong-tu-nam-hoc-2025-2026-153/?download=1&id=0",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn văn bản hướng dẫn giáo dục hòa nhập năm học 2025-2026; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-037",
    "name": "Soul Smile Center",
    "city": "Đà Nẵng",
    "district": "Cẩm Lệ",
    "address": "74 Bùi Kỷ, Cẩm Lệ, TP Đà Nẵng",
    "phone": "",
    "email": "",
    "website": "https://sanvieclamdanang.com/soul-smile-center-tuyen-dung-giao-vien-can-thiep-tap-luyen-cho-tre-em-95878.html",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "",
    "model": "Can thiệp, tập luyện cho trẻ đặc biệt",
    "lat": 16.02395,
    "lng": 108.2148,
    "status": "Ready",
    "source": "https://sanvieclamdanang.com/soul-smile-center-tuyen-dung-giao-vien-can-thiep-tap-luyen-cho-tre-em-95878.html",
    "verifyStatus": "Nguồn tuyển dụng - cần xác minh",
    "note": "Cần tìm nguồn chính thức/Facebook để xác minh trước khi publish"
  },
  {
    "id": "AI4A-038",
    "name": "Trung tâm Nhân Hòa - Cơ sở Gò Vấp",
    "city": "TP.HCM",
    "district": "Gò Vấp",
    "address": "16 Đường Số 18, Phường Thông Tây Hội, Quận Gò Vấp, TP.HCM",
    "phone": "028.6653.7779; 098.717.4279",
    "email": "trungtamnhanhoa2014@gmail.com",
    "website": "https://trungtamnhanhoa.vn/gioi-thieu-ve-trung-tam-nhan-hoa/",
    "type": "Trung tâm giáo dục hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "",
    "model": "Can thiệp sớm, can thiệp cá nhân 1-1, phát triển ngôn ngữ, hành vi, giao tiếp cho trẻ rối loạn phát triển",
    "lat": 10.85053,
    "lng": 106.65962,
    "status": "Ready",
    "source": "https://trungtamnhanhoa.vn/gioi-thieu-ve-trung-tam-nhan-hoa/",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn chính thức Nhân Hòa, crawl 2026-05-20"
  },
  {
    "id": "AI4A-039",
    "name": "Trung tâm Nhân Hòa - Cơ sở Tân Bình",
    "city": "TP.HCM",
    "district": "Tân Bình",
    "address": "58 Thiên Phước, Phường Tân Hòa, Quận Tân Bình, TP.HCM",
    "phone": "028.6653.7779; 098.717.4279",
    "email": "trungtamnhanhoa2014@gmail.com",
    "website": "https://trungtamnhanhoa.vn/gioi-thieu-ve-trung-tam-nhan-hoa/",
    "type": "Trung tâm giáo dục hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "",
    "model": "Can thiệp sớm, can thiệp cá nhân 1-1, phát triển ngôn ngữ, hành vi, giao tiếp cho trẻ rối loạn phát triển",
    "lat": 10.7878,
    "lng": 106.65362,
    "status": "Ready",
    "source": "https://trungtamnhanhoa.vn/gioi-thieu-ve-trung-tam-nhan-hoa/",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn chính thức Nhân Hòa, crawl 2026-05-20"
  },
  {
    "id": "AI4A-040",
    "name": "Trung tâm Nhân Hòa - Cơ sở Hóc Môn",
    "city": "TP.HCM",
    "district": "Hóc Môn",
    "address": "363/19 Lê Thị Hà, Hóc Môn, TP.HCM",
    "phone": "028.6653.7779; 098.717.4279",
    "email": "trungtamnhanhoa2014@gmail.com",
    "website": "https://trungtamnhanhoa.vn/gioi-thieu-ve-trung-tam-nhan-hoa/",
    "type": "Trung tâm giáo dục hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "",
    "model": "Can thiệp sớm, can thiệp cá nhân 1-1, phát triển ngôn ngữ, hành vi, giao tiếp cho trẻ rối loạn phát triển",
    "lat": 10.891,
    "lng": 106.59632,
    "status": "Ready",
    "source": "https://trungtamnhanhoa.vn/gioi-thieu-ve-trung-tam-nhan-hoa/",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn chính thức Nhân Hòa, crawl 2026-05-20"
  },
  {
    "id": "AI4A-041",
    "name": "Trung tâm Nhân Hòa - Cơ sở Quận 12 Tô Ký",
    "city": "TP.HCM",
    "district": "Quận 12",
    "address": "A29 Đường Tô Ký, Phường Trung Mỹ Tây, Quận 12, TP.HCM",
    "phone": "028.6653.7779; 098.717.4279",
    "email": "trungtamnhanhoa2014@gmail.com",
    "website": "https://trungtamnhanhoa.vn/gioi-thieu-ve-trung-tam-nhan-hoa/",
    "type": "Trung tâm giáo dục hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "",
    "model": "Can thiệp sớm, can thiệp cá nhân 1-1, phát triển ngôn ngữ, hành vi, giao tiếp cho trẻ rối loạn phát triển",
    "lat": 10.85968,
    "lng": 106.62518,
    "status": "Ready",
    "source": "https://trungtamnhanhoa.vn/gioi-thieu-ve-trung-tam-nhan-hoa/",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn chính thức Nhân Hòa, crawl 2026-05-20"
  },
  {
    "id": "AI4A-042",
    "name": "Trung tâm Nhân Hòa - Cơ sở Quận 12 Lê Thị Riêng",
    "city": "TP.HCM",
    "district": "Quận 12",
    "address": "A92 Lê Thị Riêng, Phường Thới An, Quận 12, TP.HCM",
    "phone": "028.6653.7779; 098.717.4279",
    "email": "trungtamnhanhoa2014@gmail.com",
    "website": "https://trungtamnhanhoa.vn/gioi-thieu-ve-trung-tam-nhan-hoa/",
    "type": "Trung tâm giáo dục hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "",
    "model": "Can thiệp sớm, can thiệp cá nhân 1-1, phát triển ngôn ngữ, hành vi, giao tiếp cho trẻ rối loạn phát triển",
    "lat": 10.88056,
    "lng": 106.6502,
    "status": "Ready",
    "source": "https://trungtamnhanhoa.vn/gioi-thieu-ve-trung-tam-nhan-hoa/",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn chính thức Nhân Hòa, crawl 2026-05-20"
  },
  {
    "id": "AI4A-043",
    "name": "Trung tâm Nhân Hòa - Cơ sở Bình Tân",
    "city": "TP.HCM",
    "district": "Bình Tân",
    "address": "16 Đường 5C, Quận Bình Tân, TP.HCM",
    "phone": "028.6653.7779; 098.717.4279",
    "email": "trungtamnhanhoa2014@gmail.com",
    "website": "https://trungtamnhanhoa.vn/gioi-thieu-ve-trung-tam-nhan-hoa/",
    "type": "Trung tâm giáo dục hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "",
    "model": "Can thiệp sớm, can thiệp cá nhân 1-1, phát triển ngôn ngữ, hành vi, giao tiếp cho trẻ rối loạn phát triển",
    "lat": 10.75888,
    "lng": 106.59956,
    "status": "Ready",
    "source": "https://trungtamnhanhoa.vn/gioi-thieu-ve-trung-tam-nhan-hoa/",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn chính thức Nhân Hòa, crawl 2026-05-20"
  },
  {
    "id": "AI4A-044",
    "name": "Trung tâm Can thiệp sớm Happy House",
    "city": "Bình Dương",
    "district": "Thủ Dầu Một",
    "address": "Đường 15/16 Ngô Gia Tự, Phường Chánh Nghĩa, TP Thủ Dầu Một, Bình Dương",
    "phone": "0353.368.779",
    "email": "",
    "website": "https://canthiepsombinhduong.com/",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "15 tháng - 12 tuổi",
    "model": "Can thiệp chuyên sâu cho trẻ chậm nói, tự kỷ",
    "lat": 10.98139,
    "lng": 106.6641,
    "status": "Need verify",
    "source": "https://citytowerbinhduong.com/cac-truong-chuyen-biet-tai-binh-duong/",
    "verifyStatus": "Nguồn thứ cấp - cần xác minh",
    "note": "Có website riêng; thông tin địa chỉ/điện thoại lấy từ bài tổng hợp"
  },
  {
    "id": "AI4A-045",
    "name": "Trung tâm Can thiệp sớm và Giáo dục hòa nhập trẻ đặc biệt Tuệ Đức",
    "city": "Bình Dương",
    "district": "Thủ Dầu Một",
    "address": "Số 52 đường N13, KDC Phú Hòa 1, TP Thủ Dầu Một, Bình Dương",
    "phone": "0379.456.388",
    "email": "",
    "website": "https://giaoducdacbiettueduc.edu.vn/",
    "type": "Trung tâm can thiệp / giáo dục hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "20 tháng - 8 tuổi",
    "model": "Can thiệp 1-1, học nhóm, bán trú và học theo giờ",
    "lat": 10.97459,
    "lng": 106.68226,
    "status": "Need verify",
    "source": "https://citytowerbinhduong.com/cac-truong-chuyen-biet-tai-binh-duong/",
    "verifyStatus": "Nguồn thứ cấp - cần xác minh",
    "note": "Cần đối chiếu website chính thức trước khi publish"
  },
  {
    "id": "AI4A-046",
    "name": "Trung tâm Can thiệp sớm Thanh An",
    "city": "Bình Dương",
    "district": "Thủ Dầu Một",
    "address": "Số 1 đường Lào Cai, Phường Chánh Nghĩa, TP Thủ Dầu Một, Bình Dương",
    "phone": "0765.073.633",
    "email": "",
    "website": "",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "18 tháng - 10 tuổi",
    "model": "Can thiệp trẻ tự kỷ, chậm nói, tăng giảm chú ý",
    "lat": 10.97421,
    "lng": 106.66458,
    "status": "Need verify",
    "source": "https://citytowerbinhduong.com/cac-truong-chuyen-biet-tai-binh-duong/",
    "verifyStatus": "Nguồn thứ cấp - cần xác minh",
    "note": "Cần tìm fanpage/website chính thức"
  },
  {
    "id": "AI4A-047",
    "name": "Trung tâm Sống Trẻ - Phú Lợi",
    "city": "Bình Dương",
    "district": "Thủ Dầu Một",
    "address": "Số 80 Trịnh Hoài Đức, Phường Phú Lợi, TP Thủ Dầu Một, Bình Dương",
    "phone": "0983.907.185",
    "email": "",
    "website": "https://songtre.edu.vn/",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "2 - 10 tuổi",
    "model": "Can thiệp sớm cho trẻ có nhu cầu đặc biệt",
    "lat": 10.98262,
    "lng": 106.67767,
    "status": "Need verify",
    "source": "https://citytowerbinhduong.com/cac-truong-chuyen-biet-tai-binh-duong/",
    "verifyStatus": "Nguồn thứ cấp - cần xác minh",
    "note": "Cần đối chiếu website chính thức trước khi publish"
  },
  {
    "id": "AI4A-048",
    "name": "Trung tâm Can thiệp sớm An Nhiên - Biên Hòa",
    "city": "Đồng Nai",
    "district": "Biên Hòa",
    "address": "847/33 Nguyễn Ái Quốc, Khu phố 1, Tân Hiệp, Biên Hòa, Đồng Nai",
    "phone": "",
    "email": "",
    "website": "https://baodongnai.com.vn/doanh-nhan-doanh-nghiep/202405/trung-tam-can-thiep-som-an-nhien-va-nhung-khat-vong-giup-tre-tu-ky-hoa-nhap-cong-dong-1e73c51/",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "",
    "model": "Can thiệp sớm cho trẻ tự kỷ, hỗ trợ hòa nhập cộng đồng",
    "lat": 10.96184,
    "lng": 106.86243,
    "status": "Ready",
    "source": "https://baodongnai.com.vn/doanh-nhan-doanh-nghiep/202405/trung-tam-can-thiep-som-an-nhien-va-nhung-khat-vong-giup-tre-tu-ky-hoa-nhap-cong-dong-1e73c51/",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn Báo Đồng Nai, crawl 2026-05-20"
  },
  {
    "id": "AI4A-049",
    "name": "Trung tâm Can thiệp sớm Từng Bước Nhỏ - Cơ sở 1",
    "city": "Cần Thơ",
    "district": "Tân An",
    "address": "22/B30, KDC 91B, Phường Tân An, TP Cần Thơ",
    "phone": "0984.627.205",
    "email": "",
    "website": "https://top3.vn/trung-tam-can-thiep-som-uy-tin-can-tho-trung-tam-can-thiep-som-tung-buoc-nho",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "16 tháng - 9 tuổi",
    "model": "Can thiệp chậm nói, rối loạn phổ tự kỷ, ADHD, rối loạn ngôn ngữ",
    "lat": 10.02378,
    "lng": 105.76175,
    "status": "Need verify",
    "source": "https://top3.vn/trung-tam-can-thiep-som-uy-tin-can-tho-trung-tam-can-thiep-som-tung-buoc-nho",
    "verifyStatus": "Nguồn thứ cấp - cần xác minh",
    "note": "Thông tin địa chỉ nằm trong ảnh OCR của bài viết"
  },
  {
    "id": "AI4A-050",
    "name": "Trung tâm Can thiệp sớm Từng Bước Nhỏ - Cơ sở 2",
    "city": "Cần Thơ",
    "district": "An Bình",
    "address": "98B, Đường số 5, KDC Hồng Phát, An Bình, TP Cần Thơ",
    "phone": "0984.627.205",
    "email": "",
    "website": "https://top3.vn/trung-tam-can-thiep-som-uy-tin-can-tho-trung-tam-can-thiep-som-tung-buoc-nho",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "16 tháng - 9 tuổi",
    "model": "Can thiệp chậm nói, rối loạn phổ tự kỷ, ADHD, rối loạn ngôn ngữ",
    "lat": 10.0279,
    "lng": 105.74355,
    "status": "Need verify",
    "source": "https://top3.vn/trung-tam-can-thiep-som-uy-tin-can-tho-trung-tam-can-thiep-som-tung-buoc-nho",
    "verifyStatus": "Nguồn thứ cấp - cần xác minh",
    "note": "Thông tin địa chỉ nằm trong ảnh OCR của bài viết"
  },
  {
    "id": "AI4A-051",
    "name": "Trung tâm Hỗ trợ phát triển giáo dục hòa nhập Hoa Sao",
    "city": "Quảng Ninh",
    "district": "Việt Hưng",
    "address": "Số 11, tổ 2, khu 3B, Phường Việt Hưng, Tỉnh Quảng Ninh",
    "phone": "0977.155.637",
    "email": "",
    "website": "https://masothue.com/5701989366-trung-tam-ho-tro-phat-trien-giao-duc-hoa-nhap-hoa-sao",
    "type": "Trung tâm giáo dục hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "",
    "model": "Hỗ trợ phát triển giáo dục hòa nhập",
    "lat": 21.00873,
    "lng": 107.12628,
    "status": "Ready",
    "source": "https://masothue.com/5701989366-trung-tam-ho-tro-phat-trien-giao-duc-hoa-nhap-hoa-sao",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn mã số thuế"
  },
  {
    "id": "AI4A-052",
    "name": "Trung tâm Hỗ trợ phát triển giáo dục hòa nhập Tâm Phúc",
    "city": "Bắc Ninh",
    "district": "Vũ Ninh",
    "address": "Số 128 Lạc Long Quân, Phường Vũ Ninh, Thành phố Bắc Ninh, Bắc Ninh",
    "phone": "",
    "email": "",
    "website": "https://hoptackinhdoanh.com/danh-ba-doanh-nghiep/trung-tam-ho-tro-phat-trien-giao-duc-hoa-nhap-tam-phuc-R0WHMY936B",
    "type": "Trung tâm giáo dục hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "",
    "model": "Hỗ trợ phát triển giáo dục hòa nhập",
    "lat": 21.18621,
    "lng": 106.06345,
    "status": "Need verify",
    "source": "https://hoptackinhdoanh.com/danh-ba-doanh-nghiep/trung-tam-ho-tro-phat-trien-giao-duc-hoa-nhap-tam-phuc-R0WHMY936B",
    "verifyStatus": "Nguồn thứ cấp - cần xác minh",
    "note": "Nguồn danh bạ doanh nghiệp"
  },
  {
    "id": "AI4A-053",
    "name": "Công ty TNHH Trung tâm Can thiệp sớm Cá Heo",
    "city": "Lâm Đồng",
    "district": "Đà Lạt",
    "address": "Lô B1 KQH Hải Thượng - Ba Tháng Hai, Phường Xuân Hương - Đà Lạt, Tỉnh Lâm Đồng",
    "phone": "",
    "email": "",
    "website": "https://xinvoice.vn/mst/5801570642-cong-ty-tnhh-trung-tam-can-thiep-som-ca-heo",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "",
    "model": "Can thiệp trẻ chậm phát triển ngôn ngữ/trí tuệ, rối loạn phổ tự kỷ, ADHD, rối loạn cảm xúc/hành vi",
    "lat": 11.94416,
    "lng": 108.42932,
    "status": "Ready",
    "source": "https://xinvoice.vn/mst/5801570642-cong-ty-tnhh-trung-tam-can-thiep-som-ca-heo",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn mã số thuế"
  },
  {
    "id": "AI4A-054",
    "name": "Trường dạy trẻ điếc Hải Phòng",
    "city": "Hải Phòng",
    "district": "Lê Chân",
    "address": "Số 3D Nguyễn Đức Cảnh, Quận Lê Chân, Hải Phòng",
    "phone": "031.3854.286",
    "email": "",
    "website": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "type": "Trường chuyên biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "",
    "model": "Giáo dục trẻ khiếm thính",
    "lat": 20.8543,
    "lng": 106.6764,
    "status": "Need verify",
    "source": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "verifyStatus": "Nguồn cũ - cần xác minh",
    "note": "Nguồn danh sách 2012"
  },
  {
    "id": "AI4A-055",
    "name": "Trường trẻ em khuyết tật Thái Bình",
    "city": "Thái Bình",
    "district": "Thái Bình",
    "address": "Số 271 Lý Bôn, TP Thái Bình, Thái Bình",
    "phone": "036.831.378",
    "email": "",
    "website": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "type": "Trường chuyên biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "",
    "model": "Dạy chữ, dạy nghề cho trẻ khuyết tật",
    "lat": 20.44615,
    "lng": 106.34252,
    "status": "Need verify",
    "source": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "verifyStatus": "Nguồn cũ - cần xác minh",
    "note": "Nguồn danh sách 2012"
  },
  {
    "id": "AI4A-056",
    "name": "Trung tâm giáo dục trẻ em thiệt thòi Thái Nguyên",
    "city": "Thái Nguyên",
    "district": "Thái Nguyên",
    "address": "Phường Tân Thịnh, TP Thái Nguyên, Thái Nguyên",
    "phone": "0280.851.613",
    "email": "",
    "website": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "type": "Trung tâm giáo dục đặc biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "",
    "model": "Giáo dục trẻ em thiệt thòi",
    "lat": 21.5853,
    "lng": 105.80632,
    "status": "Need verify",
    "source": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "verifyStatus": "Nguồn cũ - cần xác minh",
    "note": "Nguồn danh sách 2012"
  },
  {
    "id": "AI4A-057",
    "name": "Trung tâm nuôi dạy trẻ em khuyết tật Bắc Ninh",
    "city": "Bắc Ninh",
    "district": "Bắc Ninh",
    "address": "Số 61 Thiên Đức, TP Bắc Ninh, Bắc Ninh",
    "phone": "0241.3822.378",
    "email": "",
    "website": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "type": "Trung tâm giáo dục đặc biệt",
    "layer": "Trường chuyên biệt",
    "color": "Đỏ",
    "ages": "",
    "model": "Nuôi dạy trẻ em khuyết tật",
    "lat": 21.1869,
    "lng": 106.0767,
    "status": "Need verify",
    "source": "https://www.traimoxanh.com/danh-sach-cac-truong-chuyen-biet-tai-ha-noi-tp-ho-chi-minh-va-cac-tinh-phia-bac/",
    "verifyStatus": "Nguồn cũ - cần xác minh",
    "note": "Nguồn danh sách 2012"
  },
  {
    "id": "AI4A-058",
    "name": "Trung tâm hỗ trợ phát triển giáo dục hòa nhập Hoa Xương Rồng",
    "city": "Đà Nẵng",
    "district": "Hòa Xuân",
    "address": "74 Nguyễn Quang Diêu, Hòa Xuân, Đà Nẵng",
    "phone": "",
    "email": "",
    "website": "https://tieuhocdongphu.edu.vn/laws/detail/V-v-huong-dan-cong-tac-giao-duc-hoa-nhap-cho-hoc-sinh-khuyet-tat-tai-cac-co-so-giao-duc-pho-thong-tu-nam-hoc-2025-2026-153/?download=1&id=0",
    "type": "Trung tâm giáo dục hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "",
    "model": "Hỗ trợ phát triển giáo dục hòa nhập",
    "lat": 15.99744,
    "lng": 108.22178,
    "status": "Ready",
    "source": "https://tieuhocdongphu.edu.vn/laws/detail/V-v-huong-dan-cong-tac-giao-duc-hoa-nhap-cho-hoc-sinh-khuyet-tat-tai-cac-co-so-giao-duc-pho-thong-tu-nam-hoc-2025-2026-153/?download=1&id=0",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn văn bản hướng dẫn giáo dục hòa nhập năm học 2025-2026"
  },
  {
    "id": "AI4A-059",
    "name": "Trung tâm Hỗ trợ Phát triển Giáo dục Hòa nhập tư thục Ánh Dương",
    "city": "Đà Nẵng",
    "district": "Hội An",
    "address": "18B Phước Trung, Phường Hội An, TP Đà Nẵng",
    "phone": "",
    "email": "",
    "website": "https://tieuhocdongphu.edu.vn/laws/detail/V-v-huong-dan-cong-tac-giao-duc-hoa-nhap-cho-hoc-sinh-khuyet-tat-tai-cac-co-so-giao-duc-pho-thong-tu-nam-hoc-2025-2026-153/?download=1&id=0",
    "type": "Trung tâm giáo dục hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "",
    "model": "Hỗ trợ phát triển giáo dục hòa nhập",
    "lat": 15.879,
    "lng": 108.338,
    "status": "Need verify",
    "source": "https://tieuhocdongphu.edu.vn/laws/detail/V-v-huong-dan-cong-tac-giao-duc-hoa-nhap-cho-hoc-sinh-khuyet-tat-tai-cac-co-so-giao-duc-pho-thong-tu-nam-hoc-2025-2026-153/?download=1&id=0",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn văn bản sau sáp nhập, cần đối chiếu địa danh; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-060",
    "name": "Trung tâm GDĐT Ngôn ngữ ký hiệu và Hỗ trợ Người Điếc Miền Trung",
    "city": "Đà Nẵng",
    "district": "Hải Châu",
    "address": "28 Châu Thượng Văn, Phường Hòa Cường, TP Đà Nẵng",
    "phone": "",
    "email": "",
    "website": "https://tieuhocdongphu.edu.vn/laws/detail/V-v-huong-dan-cong-tac-giao-duc-hoa-nhap-cho-hoc-sinh-khuyet-tat-tai-cac-co-so-giao-duc-pho-thong-tu-nam-hoc-2025-2026-153/?download=1&id=0",
    "type": "Trung tâm hỗ trợ người điếc",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "",
    "model": "Giáo dục đào tạo ngôn ngữ ký hiệu và hỗ trợ người điếc",
    "lat": 16.04882,
    "lng": 108.21873,
    "status": "Ready",
    "source": "https://tieuhocdongphu.edu.vn/laws/detail/V-v-huong-dan-cong-tac-giao-duc-hoa-nhap-cho-hoc-sinh-khuyet-tat-tai-cac-co-so-giao-duc-pho-thong-tu-nam-hoc-2025-2026-153/?download=1&id=0",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn văn bản hướng dẫn giáo dục hòa nhập năm học 2025-2026"
  },
  {
    "id": "AI4A-061",
    "name": "Trung tâm Hỗ trợ Phát triển giáo dục hòa nhập tư thục Hoa Mặt Trời",
    "city": "Đà Nẵng",
    "district": "Hương Trà",
    "address": "Tổ 6, Khối phố Hương Sơn, Phường Hương Trà, TP Đà Nẵng",
    "phone": "",
    "email": "",
    "website": "https://tieuhocdongphu.edu.vn/laws/detail/V-v-huong-dan-cong-tac-giao-duc-hoa-nhap-cho-hoc-sinh-khuyet-tat-tai-cac-co-so-giao-duc-pho-thong-tu-nam-hoc-2025-2026-153/?download=1&id=0",
    "type": "Trung tâm giáo dục hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "",
    "model": "Hỗ trợ phát triển giáo dục hòa nhập",
    "lat": 15.622,
    "lng": 108.397,
    "status": "Need verify",
    "source": "https://tieuhocdongphu.edu.vn/laws/detail/V-v-huong-dan-cong-tac-giao-duc-hoa-nhap-cho-hoc-sinh-khuyet-tat-tai-cac-co-so-giao-duc-pho-thong-tu-nam-hoc-2025-2026-153/?download=1&id=0",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn văn bản sau sáp nhập, cần đối chiếu địa danh; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-062",
    "name": "Trung tâm hỗ trợ và Giáo dục hòa nhập đối với trẻ khiếm thính Quảng Nam",
    "city": "Đà Nẵng",
    "district": "Điện Bàn Đông",
    "address": "Khối phố Cổ Đông An, Phường Điện Bàn Đông, TP Đà Nẵng",
    "phone": "",
    "email": "",
    "website": "https://tieuhocdongphu.edu.vn/laws/detail/V-v-huong-dan-cong-tac-giao-duc-hoa-nhap-cho-hoc-sinh-khuyet-tat-tai-cac-co-so-giao-duc-pho-thong-tu-nam-hoc-2025-2026-153/?download=1&id=0",
    "type": "Trung tâm giáo dục hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "",
    "model": "Hỗ trợ và giáo dục hòa nhập đối với trẻ khiếm thính",
    "lat": 15.887,
    "lng": 108.301,
    "status": "Need verify",
    "source": "https://tieuhocdongphu.edu.vn/laws/detail/V-v-huong-dan-cong-tac-giao-duc-hoa-nhap-cho-hoc-sinh-khuyet-tat-tai-cac-co-so-giao-duc-pho-thong-tu-nam-hoc-2025-2026-153/?download=1&id=0",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn văn bản sau sáp nhập, cần đối chiếu địa danh; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-063",
    "name": "Trung tâm Hỗ trợ Phát triển giáo dục hòa nhập tư thục Hoa Mặt Trời Núi Thành",
    "city": "Đà Nẵng",
    "district": "Núi Thành",
    "address": "Thôn Văn hóa Vân Trai, Xã Núi Thành, TP Đà Nẵng",
    "phone": "",
    "email": "",
    "website": "https://tieuhocdongphu.edu.vn/laws/detail/V-v-huong-dan-cong-tac-giao-duc-hoa-nhap-cho-hoc-sinh-khuyet-tat-tai-cac-co-so-giao-duc-pho-thong-tu-nam-hoc-2025-2026-153/?download=1&id=0",
    "type": "Trung tâm giáo dục hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "",
    "model": "Hỗ trợ phát triển giáo dục hòa nhập",
    "lat": 15.433,
    "lng": 108.644,
    "status": "Need verify",
    "source": "https://tieuhocdongphu.edu.vn/laws/detail/V-v-huong-dan-cong-tac-giao-duc-hoa-nhap-cho-hoc-sinh-khuyet-tat-tai-cac-co-so-giao-duc-pho-thong-tu-nam-hoc-2025-2026-153/?download=1&id=0",
    "verifyStatus": "Cần xác minh lại",
    "note": "Nguồn văn bản sau sáp nhập, cần đối chiếu địa danh; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-064",
    "name": "Trung tâm can thiệp sớm BI Center - Quận 7",
    "city": "TP.HCM",
    "district": "Quận 7",
    "address": "A35 KDC Tân Thuận Nam, Phường Phú Thuận, Quận 7, TP.HCM",
    "phone": "",
    "email": "",
    "website": "https://kiddihub.com/chi-tiet/trung-tam-can-thiep-som-bi-center-quan-7",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "2 tuổi - 15 tuổi",
    "model": "Sàng lọc, đánh giá, can thiệp, hỗ trợ giáo dục cho trẻ rối loạn phổ tự kỷ, ADHD, chậm phát triển trí tuệ, khó khăn giao tiếp",
    "lat": 10.7399,
    "lng": 106.7259,
    "status": "Need verify",
    "source": "https://kiddihub.com/chi-tiet/trung-tam-can-thiep-som-bi-center-quan-7",
    "verifyStatus": "Nguồn KiddiHub - cần xác minh",
    "note": "User xác nhận là đối tác liên kết; Google/Facebook public snippet có page BI Center; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-065",
    "name": "Can Thiệp Sớm Ms Quỳnh - Phú Thuận, Q7",
    "city": "TP.HCM",
    "district": "Quận 7",
    "address": "Số 1135/41/20/2, Đường Huỳnh Tấn Phát, Phường Phú Thuận, Quận 7, TP.HCM",
    "phone": "",
    "email": "",
    "website": "https://kiddihub.com/trung-tam-tre-dac-biet/ho-chi-minh/khu-vuc-chung-cu-ngoc-lan-quan-7",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "18 tháng - 10 tuổi",
    "model": "Can thiệp sớm, trẻ tự kỷ/chậm phát triển/chậm nói",
    "lat": 10.7357,
    "lng": 106.7323,
    "status": "Need verify",
    "source": "https://kiddihub.com/trung-tam-tre-dac-biet/ho-chi-minh/khu-vuc-chung-cu-ngoc-lan-quan-7",
    "verifyStatus": "Nguồn KiddiHub - cần xác minh",
    "note": "KiddiHub ghi Thành viên KiddiHub; cần đối chiếu fanpage/điện thoại; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-066",
    "name": "Trung tâm Can thiệp sớm Cầu Vồng - Tân Thuận Đông",
    "city": "TP.HCM",
    "district": "Quận 7",
    "address": "58/6 Võ Thị Nhờ, Phường Tân Thuận Đông, Quận 7, TP.HCM",
    "phone": "",
    "email": "",
    "website": "https://kiddihub.com/trung-tam-tre-dac-biet/ho-chi-minh/khu-vuc-duong-nguyen-van-quy-quan-7",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "18 tháng - 6 tuổi",
    "model": "Can thiệp sớm, trung tâm trẻ đặc biệt",
    "lat": 10.7487,
    "lng": 106.7292,
    "status": "Need verify",
    "source": "https://kiddihub.com/trung-tam-tre-dac-biet/ho-chi-minh/khu-vuc-duong-nguyen-van-quy-quan-7",
    "verifyStatus": "Nguồn KiddiHub - cần xác minh",
    "note": "KiddiHub ghi chưa xác minh; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-067",
    "name": "Trung tâm Can thiệp sớm Bakery - Tân Thuận",
    "city": "TP.HCM",
    "district": "Quận 7",
    "address": "Huỳnh Tấn Phát, Phường Tân Thuận, Quận 7, TP.HCM",
    "phone": "",
    "email": "",
    "website": "https://kiddihub.com/trung-tam-tre-dac-biet/ho-chi-minh/khu-vuc-duong-nguyen-van-quy-quan-7",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "",
    "model": "Can thiệp sớm, trung tâm trẻ đặc biệt",
    "lat": 10.744,
    "lng": 106.729,
    "status": "Need verify",
    "source": "https://kiddihub.com/trung-tam-tre-dac-biet/ho-chi-minh/khu-vuc-duong-nguyen-van-quy-quan-7",
    "verifyStatus": "Nguồn KiddiHub - cần xác minh",
    "note": "Địa chỉ chưa đủ số nhà; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-068",
    "name": "Trung tâm Nghiên cứu Ứng dụng Can thiệp Tâm lý Trẻ Rối loạn Phát triển Tường Minh - Tân Hưng",
    "city": "TP.HCM",
    "district": "Quận 7",
    "address": "Số 25, Đường 44, Phường Tân Hưng, Quận 7, TP.HCM",
    "phone": "",
    "email": "",
    "website": "https://kiddihub.com/chi-tiet/trung-tam-giao-duc-tuong-minh",
    "type": "Trung tâm can thiệp / giáo dục hòa nhập",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "2 tuổi - 15 tuổi",
    "model": "Thăm khám, chẩn đoán, đánh giá nhận thức/hành vi/kỹ năng sống, can thiệp sớm, đồng hành tại trường học và cộng đồng",
    "lat": 10.7436,
    "lng": 106.7008,
    "status": "Need verify",
    "source": "https://kiddihub.com/chi-tiet/trung-tam-giao-duc-tuong-minh",
    "verifyStatus": "Nguồn KiddiHub - cần xác minh",
    "note": "KiddiHub có trang chi tiết; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-069",
    "name": "Trung tâm Can thiệp Hạnh Phúc - Quận 7",
    "city": "TP.HCM",
    "district": "Quận 7",
    "address": "300/25A Nguyễn Văn Linh, Phường Bình Thuận, Quận 7, TP.HCM",
    "phone": "",
    "email": "",
    "website": "https://kiddihub.com/trung-tam-tre-dac-biet/ho-chi-minh/khu-vuc-benh-vien-quan-7-quan-7",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "3 tuổi - 12 tuổi",
    "model": "Can thiệp trẻ đặc biệt",
    "lat": 10.7418,
    "lng": 106.7115,
    "status": "Need verify",
    "source": "https://kiddihub.com/trung-tam-tre-dac-biet/ho-chi-minh/khu-vuc-benh-vien-quan-7-quan-7",
    "verifyStatus": "Nguồn KiddiHub - cần xác minh",
    "note": "KiddiHub ghi chưa xác minh; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-070",
    "name": "Trung Tâm Can Thiệp Sớm Sunshine - Tân Qui Đông",
    "city": "TP.HCM",
    "district": "Quận 7",
    "address": "110 Đường 40, KDC Tân Qui Đông, Phường Tân Phong, Quận 7, TP.HCM",
    "phone": "",
    "email": "",
    "website": "https://kiddihub.com/chi-tiet/trung-tam-can-thiep-som-sunshine-tan-qui-dong-quan-7",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "1 tuổi - 5 tuổi",
    "model": "Can thiệp sớm, trung tâm trẻ đặc biệt",
    "lat": 10.7331,
    "lng": 106.7048,
    "status": "Need verify",
    "source": "https://kiddihub.com/chi-tiet/trung-tam-can-thiep-som-sunshine-tan-qui-dong-quan-7",
    "verifyStatus": "Nguồn KiddiHub - cần xác minh",
    "note": "KiddiHub ghi chưa xác minh; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-071",
    "name": "SENBOX - Trung Tâm Học Tập Tiêu Chuẩn Quốc Tế",
    "city": "TP.HCM",
    "district": "Quận 7",
    "address": "Số 8 Đường 56, Khu định cư Tân Quy Đông, Quận 7, TP.HCM",
    "phone": "",
    "email": "",
    "website": "https://kiddihub.com/trung-tam-tre-dac-biet/ho-chi-minh/khu-vuc-duong-nguyen-thi-thap-quan-7",
    "type": "Trung tâm học tập / can thiệp sớm",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "2 tuổi - 16 tuổi",
    "model": "Kỹ năng sống, can thiệp sớm, phát triển",
    "lat": 10.7329,
    "lng": 106.7065,
    "status": "Need verify",
    "source": "https://kiddihub.com/trung-tam-tre-dac-biet/ho-chi-minh/khu-vuc-duong-nguyen-thi-thap-quan-7",
    "verifyStatus": "Nguồn KiddiHub - cần xác minh",
    "note": "KiddiHub ghi Thành viên KiddiHub; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-072",
    "name": "Học viện Phát triển Ngôn Ngữ Speech - Tân Phú",
    "city": "TP.HCM",
    "district": "Quận 7",
    "address": "Shophouse 02, Lô M5, Midtown Phú Mỹ Hưng, Nguyễn Lương Bằng, Phường Tân Phú, Quận 7, TP.HCM",
    "phone": "",
    "email": "",
    "website": "https://kiddihub.com/trung-tam-tre-dac-biet/ho-chi-minh/khu-vuc-duong-tan-phu-quan-7",
    "type": "Trung tâm ngôn ngữ / can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "18 tháng - 15 tuổi",
    "model": "Phát triển ngôn ngữ, can thiệp trẻ đặc biệt",
    "lat": 10.7309,
    "lng": 106.7242,
    "status": "Need verify",
    "source": "https://kiddihub.com/trung-tam-tre-dac-biet/ho-chi-minh/khu-vuc-duong-tan-phu-quan-7",
    "verifyStatus": "Nguồn KiddiHub - cần xác minh",
    "note": "Cần đối chiếu website/fanpage chính thức; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-073",
    "name": "Trung Tâm Giáo Dục Hòa Nhập Cầu Vồng - Phúc Xá",
    "city": "Hà Nội",
    "district": "Ba Đình",
    "address": "Số 47 Ngõ 22 Phố Phúc Xá, Phường Phúc Xá, Quận Ba Đình, Hà Nội",
    "phone": "",
    "email": "",
    "website": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "type": "Trung tâm giáo dục hòa nhập",
    "layer": "Hòa nhập",
    "color": "Xanh lá",
    "ages": "12 tháng - 12 tuổi",
    "model": "Giáo dục hòa nhập, can thiệp sớm",
    "lat": 21.0457,
    "lng": 105.8465,
    "status": "Need verify",
    "source": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "verifyStatus": "Nguồn KiddiHub - cần xác minh",
    "note": "KiddiHub ghi Thành viên KiddiHub; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-074",
    "name": "Trung tâm Nghiên cứu và Ứng dụng Tâm lý - Giáo dục Châu Giang - Phương Mai",
    "city": "Hà Nội",
    "district": "Đống Đa",
    "address": "Số 44, Ngõ 15, Phố Phương Mai, Phường Phương Mai, Quận Đống Đa, Hà Nội",
    "phone": "",
    "email": "",
    "website": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "type": "Trung tâm tâm lý giáo dục",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "12 tháng - 18 tuổi",
    "model": "Tâm lý giáo dục, can thiệp trẻ đặc biệt",
    "lat": 21.0036,
    "lng": 105.8375,
    "status": "Need verify",
    "source": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "verifyStatus": "Nguồn KiddiHub - cần xác minh",
    "note": "KiddiHub ghi Thành viên KiddiHub; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-075",
    "name": "Hệ Thống Giáo Dục đặc biệt Mai Hương - Xuân Đỉnh",
    "city": "Hà Nội",
    "district": "Bắc Từ Liêm",
    "address": "Số 29, Ngách 65 Ngõ 207, Đường Xuân Đỉnh, Phường Xuân Đỉnh, Quận Bắc Từ Liêm, Hà Nội",
    "phone": "",
    "email": "",
    "website": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "type": "Hệ thống giáo dục đặc biệt",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "12 tháng - 6 tuổi",
    "model": "Can thiệp trẻ tự kỷ, giáo dục đặc biệt",
    "lat": 21.0818,
    "lng": 105.7883,
    "status": "Need verify",
    "source": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "verifyStatus": "Nguồn KiddiHub - cần xác minh",
    "note": "KiddiHub ghi Thành viên KiddiHub; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-076",
    "name": "Trị liệu ngôn ngữ Tâm An Bình - KĐT Văn Phú",
    "city": "Hà Nội",
    "district": "Hà Đông",
    "address": "Số 18 lô TT24, Khu đô thị Văn Phú, Phường Kiến Hưng, Hà Nội",
    "phone": "",
    "email": "",
    "website": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "type": "Trung tâm trị liệu ngôn ngữ",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "2 tuổi - 16 tuổi",
    "model": "Trị liệu ngôn ngữ, can thiệp sớm",
    "lat": 20.9619,
    "lng": 105.7608,
    "status": "Need verify",
    "source": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "verifyStatus": "Nguồn KiddiHub - cần xác minh",
    "note": "KiddiHub ghi Thành viên KiddiHub; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-077",
    "name": "Trung Tâm Nghiên Cứu Ứng Dụng Tâm Lý Học, Can Thiệp Minh Trí - Thịnh Liệt",
    "city": "Hà Nội",
    "district": "Hoàng Mai",
    "address": "Số 44 ngách 197 ngõ 42 Thịnh Liệt, Phường Thịnh Liệt, Quận Hoàng Mai, Hà Nội",
    "phone": "",
    "email": "",
    "website": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "type": "Trung tâm tâm lý / can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "2 tuổi - 9 tuổi",
    "model": "Tâm lý học, can thiệp trẻ đặc biệt",
    "lat": 20.9709,
    "lng": 105.8433,
    "status": "Need verify",
    "source": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "verifyStatus": "Nguồn KiddiHub - cần xác minh",
    "note": "KiddiHub ghi Thành viên KiddiHub; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-078",
    "name": "Trung Tâm Nghiên Cứu Ứng Dụng Tâm Lý Giáo Dục Nhà Bình An - Gia Thụy",
    "city": "Hà Nội",
    "district": "Long Biên",
    "address": "Số 4 Ngõ 489 Nguyễn Văn Cừ, Phường Gia Thụy, Quận Long Biên, Hà Nội",
    "phone": "",
    "email": "",
    "website": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "type": "Trung tâm tâm lý giáo dục",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "Nhỏ hơn 15 tuổi",
    "model": "Tâm lý giáo dục, can thiệp trẻ đặc biệt",
    "lat": 21.0595,
    "lng": 105.8858,
    "status": "Need verify",
    "source": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "verifyStatus": "Nguồn KiddiHub - cần xác minh",
    "note": "KiddiHub ghi Thành viên KiddiHub; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-079",
    "name": "Trung Tâm Tư Vấn Và Phát Triển Giáo Dục Đặc Biệt Đậu Nhí - Tam Trinh",
    "city": "Hà Nội",
    "district": "Hoàng Mai",
    "address": "Lô 11, NV 1-2 Gelexia Riverside, Ngõ 885 Tam Trinh, Phường Yên Sở, Quận Hoàng Mai, Hà Nội",
    "phone": "",
    "email": "",
    "website": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "type": "Trung tâm giáo dục đặc biệt",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "18 tháng - 10 tuổi",
    "model": "Tư vấn và phát triển giáo dục đặc biệt",
    "lat": 20.9786,
    "lng": 105.8697,
    "status": "Need verify",
    "source": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "verifyStatus": "Nguồn KiddiHub - cần xác minh",
    "note": "KiddiHub ghi Thành viên KiddiHub; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-080",
    "name": "Trung Tâm Can Thiệp Sớm Thảo Nguyên - Hoài Đức",
    "city": "Hà Nội",
    "district": "Hoài Đức",
    "address": "Số 123, Khu 6, Thị trấn Trạm Trôi, Huyện Hoài Đức, Hà Nội",
    "phone": "",
    "email": "",
    "website": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "18 tháng - 12 tuổi",
    "model": "Can thiệp sớm, giáo dục đặc biệt cá nhân hóa IEP",
    "lat": 21.0691,
    "lng": 105.7073,
    "status": "Need verify",
    "source": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "verifyStatus": "Nguồn KiddiHub - cần xác minh",
    "note": "KiddiHub ghi Thành viên KiddiHub; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-081",
    "name": "Trung Tâm Can Thiệp Sớm Kido - Huỳnh Thúc Kháng",
    "city": "Hà Nội",
    "district": "Đống Đa",
    "address": "Số 2 Ngách 46 Ngõ 49 Huỳnh Thúc Kháng, Phường Láng Hạ, Quận Đống Đa, Hà Nội",
    "phone": "",
    "email": "",
    "website": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "18 tháng - 10 tuổi",
    "model": "Can thiệp sớm",
    "lat": 21.0176,
    "lng": 105.8112,
    "status": "Need verify",
    "source": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "verifyStatus": "Nguồn KiddiHub - cần xác minh",
    "note": "KiddiHub ghi Thành viên KiddiHub; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-082",
    "name": "Trung tâm can thiệp sớm Niềm Tin - Định Công",
    "city": "Hà Nội",
    "district": "Hoàng Mai",
    "address": "Số nhà 04, Ngõ 17, Phố Trần Hòa, Phường Định Công, Quận Hoàng Mai, Hà Nội",
    "phone": "",
    "email": "",
    "website": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "type": "Trung tâm can thiệp",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "15 tháng - 10 tuổi",
    "model": "Can thiệp sớm",
    "lat": 20.9782,
    "lng": 105.8356,
    "status": "Need verify",
    "source": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "verifyStatus": "Nguồn KiddiHub - cần xác minh",
    "note": "KiddiHub ghi Thành viên KiddiHub; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  },
  {
    "id": "AI4A-083",
    "name": "Hệ Thống Giáo Dục đặc biệt Mai Hương - Tây Hồ",
    "city": "Hà Nội",
    "district": "Tây Hồ",
    "address": "Số 12K, Ngõ 218, Đường Lạc Long Quân, Phường Xuân La, Quận Tây Hồ, Hà Nội",
    "phone": "",
    "email": "",
    "website": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "type": "Hệ thống giáo dục đặc biệt",
    "layer": "Can thiệp sớm",
    "color": "Cam",
    "ages": "16 tháng - 8 tuổi",
    "model": "Can thiệp trẻ tự kỷ, giáo dục đặc biệt",
    "lat": 21.0649,
    "lng": 105.8099,
    "status": "Need verify",
    "source": "https://kiddihub.com/trung-tam-tre-dac-biet/ha-noi",
    "verifyStatus": "Nguồn KiddiHub - cần xác minh",
    "note": "KiddiHub ghi Thành viên KiddiHub; GPS ước lượng theo địa chỉ, cần kiểm tra lại marker trước khi publish"
  }
];
